spring:
    data:
        rest:
            base-path: /api
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        username: gen_user
        password: 19ejl95fk1
        jdbcUrl: jdbc:mysql://85.193.88.137:3306/default_db
    logging:
        level:
            org.springframework: INFO
