spring:
    data:
        rest:
            base-path: /api
    datasource:
        master:
            driverClassName: com.mysql.jdbc.Driver
            username: root
            password: pass
            jdbcUrl: jdbc:mysql://89.223.122.234:6603/testdb
        slave1:
            driverClassName: com.mysql.jdbc.Driver
            username: root
            password: pass
            jdbcUrl: jdbc:mysql://89.223.122.234:6603/testdb
        slave2:
            driverClassName: com.mysql.jdbc.Driver
            username: root
            password: pass
            jdbcUrl: jdbc:mysql://89.223.125.10:6603/testdb
    logging:
        level:
            org.springframework: INFO
